<a href="https://colab.research.google.com/github/wujh03/MSSP6070/blob/main/WeeklyModules/Week06/week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/wujh03/MSSP6070/main/data/Student%20Performance%20Data.csv"

df = pd.read_csv(url)

display(df.head())
print(df.columns.tolist())

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'math score', 'reading score', 'writing score', 'total score', 'test preparation course', 'admission prospect']

In [2]:
# Filter students whose math score is above average
filter_students = lambda data: data[
    data["math score"] > data["math score"].mean()
].copy()

# Apply the lambda function
new_df = filter_students(df)

# Display the new DataFrame
display(new_df.head())

print("Original shape:", df.shape)
print("New shape:", new_df.shape)

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high

Original shape: (1000, 10)
New shape: (493, 10)

In [3]:
print(type(new_df))

<class 'pandas.core.frame.DataFrame'>