<a href="https://colab.research.google.com/github/wujh03/MSSP6070/blob/main/Assignments/week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/wujh03/MSSP6070.git

Cloning into 'MSSP6070'...
remote: Enumerating objects: 182, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 182 (delta 26), reused 6 (delta 6), pack-reused 140 (from 1)
Receiving objects: 100% (182/182), 4.04 MiB | 10.53 MiB/s, done.
Resolving deltas: 100% (98/98), done.

In [2]:
%cd MSSP6070

/content/MSSP6070

In [3]:
!ls data

aapl.csv		  amzn.csv			  fb.csv    nflx.csv
academic_performance.csv  data_academic_performance.xlsx  goog.csv  parsed.csv

In [4]:
import pandas as pd

In [6]:
aapl = pd.read_csv('data/aapl.csv')
amzn = pd.read_csv('data/amzn.csv')
fb = pd.read_csv('data/fb.csv')
nflx = pd.read_csv('data/nflx.csv')
goog = pd.read_csv('data/goog.csv')

In [7]:
aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [8]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
nflx['ticker'] = 'NFLX'
goog['ticker'] = 'GOOG'

In [9]:
faanf = pd.concat(
    [fb, aapl, amzn, nflx, goog],
    ignore_index=True
)

faanf.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [10]:
faanf.to_csv('data/faanf.csv', index=False)

In [11]:
faanf['date'] = pd.to_datetime(faanf['date'])
faanf['volume'] = faanf['volume'].astype(int)

faanf.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [12]:
faanf = faanf.sort_values(
    by=['date', 'ticker']
).reset_index(drop=True)

faanf.head(10)

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
2 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
3 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
5 2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
6 2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
7 2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
8 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
9 2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX

In [13]:
top_7_volume = faanf.nlargest(7, 'volume')
top_7_volume

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [14]:
faanf_melted = faanf.melt(
    id_vars=['date', 'ticker']
)

faanf_melted.head(20)

         date ticker variable      value
0  2018-01-02   AAPL     open   166.9271
1  2018-01-02   AMZN     open  1172.0000
2  2018-01-02     FB     open   177.6800
3  2018-01-02   GOOG     open  1048.3400
4  2018-01-02   NFLX     open   196.1000
5  2018-01-03   AAPL     open   169.2521
6  2018-01-03   AMZN     open  1188.3000
7  2018-01-03     FB     open   181.8800
8  2018-01-03   GOOG     open  1064.3100
9  2018-01-03   NFLX     open   202.0500
10 2018-01-04   AAPL     open   169.2619
11 2018-01-04   AMZN     open  1205.0000
12 2018-01-04     FB     open   184.9000
13 2018-01-04   GOOG     open  1088.0000
14 2018-01-04   NFLX     open   206.2000
15 2018-01-05   AAPL     open   170.1448
16 2018-01-05   AMZN     open  1217.5100
17 2018-01-05     FB     open   185.5900
18 2018-01-05   GOOG     open  1094.0000
19 2018-01-05   NFLX     open   207.2500

In [15]:
faanf.to_csv('data/faanf.csv', index=False)